DEP Dependencies for CMS 6
silverstripe/recipe-testing pull request #15
Opened 2024-02-19 04:33 UTC by emteknetnz

Issue https://github.com/silverstripe/.github/issues/191

2024-02-19 21:42 UTC, GuySartorelli requested changes

2024-02-19 21:42 UTC, ChloeSartorelli commented on composer.json
> +        "silverstripe/serve": "^4",
Just remove serve, we don't want to support that on any level going forward

2024-02-19 21:51 UTC, emteknetnz commented on composer.json
> +        "silverstripe/serve": "^4",
Updated

2024-02-20 06:17 UTC, GuySartorelli approved these changes
LGTM. Failures are expected at this stage so ignoring CI.

2024-02-20 06:18 UTC, merged